### ISSUE TITLE
Invalid Details

### ISSUE THREAD

**Issue by tharnab** [Ansarimajid/College-ERP#15]
after giving the student details 
student@student.com
student@erp
saying wrong details

**Comment by Ansarimajid** [comment]
> **It's Updated now you can pull Main branch and login with given credentials...**

**And if you want to create admin credentials, you can simply run below command!**

Command for PC:
```
$  python manage.py createsuperuser
```

Command for Mac:
```
$  python3 manage.py createsuperuser
```

Command for Linux:
```
$  python3 manage.py createsuperuser
```
